openapi: 3.0.2
info:
  title: 'Longevity API'
  version: '1.0'
paths:
  /api/users/profile/me/:
    get:
      operationId: listuser_profiles
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u043F\u043E\u043B\u0443\
        \u0447\u0435\u043D\u0438\u044F \u0438\u043B\u0438 \u0440\u0435\u0434\u0430\
        \u043A\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u0441\u0432\u043E\u0435\u0433\u043E\
        \ \u043F\u0440\u043E\u0444\u0438\u043B\u044F."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
    put:
      operationId: updateuser_profile
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u043F\u043E\u043B\u0443\
        \u0447\u0435\u043D\u0438\u044F \u0438\u043B\u0438 \u0440\u0435\u0434\u0430\
        \u043A\u0442\u0438\u0440\u043E\u0432\u0430\u043D\u0438\u044F \u0438\u043D\u0444\
        \u043E\u0440\u043C\u0430\u0446\u0438\u0438 \u0441\u0432\u043E\u0435\u0433\u043E\
        \ \u043F\u0440\u043E\u0444\u0438\u043B\u044F."
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/users/profile/:
    get:
      operationId: listprofile_lists
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u043F\u043E\u043B\u0443\
        \u0447\u0435\u043D\u0438\u044F \u0441\u043F\u0438\u0441\u043A\u0430 \u043F\
        \u0440\u043E\u0444\u0438\u043B\u0435\u0439."
      parameters: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items: {}
          description: ''
      tags:
      - api
  /api/users/profile/{id}/:
    get:
      operationId: retrieveother_profile
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u043F\u043E\u043B\u0443\
        \u0447\u0435\u043D\u0438\u044F \u0438\u043D\u0444\u043E\u0440\u043C\u0430\u0446\
        \u0438\u0438 \u0447\u0443\u0436\u043E\u0433\u043E \u043F\u0440\u043E\u0444\
        \u0438\u043B\u044F."
      parameters:
      - name: id
        in: path
        required: true
        description: ''
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/users/register/:
    post:
      operationId: createregister
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u0440\u0435\u0433\u0438\
        \u0441\u0442\u0440\u0430\u0446\u0438\u0438."
      parameters: []
      requestBody:
        content:
          application/json:
            schema: {}
          application/x-www-form-urlencoded:
            schema: {}
          multipart/form-data:
            schema: {}
      responses:
        '201':
          content:
            application/json:
              schema: {}
          description: ''
      tags:
      - api
  /api/users/login/:
    post:
      operationId: createCustomTokenObtain
      description: "\u041A\u0430\u0441\u0442\u043E\u043C\u043D\u0430\u044F \u0432\u044C\
        \u044E\u0445\u0430 \u0434\u043B\u044F \u043F\u043E\u043B\u0443\u0447\u0435\
        \u043D\u0438\u044F \u0442\u043E\u043A\u0435\u043D\u0430."
      parameters: []
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
          application/json:
            schema:
              $ref: '#/components/schemas/CustomTokenObtain'
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CustomTokenObtain'
          description: ''
      tags:
      - api
  /api/users/delete/:
    delete:
      operationId: destroydelete_account
      description: "\u0424\u0443\u043D\u043A\u0446\u0438\u044F \u0443\u0434\u0430\u043B\
        \u0435\u043D\u0438\u044F \u043F\u0440\u043E\u0444\u0438\u043B\u044F."
      parameters: []
      responses:
        '204':
          description: ''
      tags:
      - api
components:
  schemas:
    CustomTokenObtain:
      type: object
      properties:
        email:
          type: string
          format: email
        password:
          type: string
          writeOnly: true
        otp_code:
          type: string
          readOnly: true
      required:
      - email
      - password
